webtalk_init -webtalk_dir /home/jorge/VivadoUSM/AXI_Adder_tree_throughput/AXI_Adder_tree_throughput.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-09-05 02:42:31" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "k53i89si8r0hfen6gf44upvpoe" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_33" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "33" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1633.915 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8,288 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1567651335000" -context "sdk\\\\hardware/1567651335000"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1567651335000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1567651335000"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1567651335000"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.2" -context "sdk\\\\hardware/1567651335000"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1567651335000"
webtalk_add_data -client sdk -key Device -value "7a100t" -context "sdk\\\\hardware/1567651335000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1567651335000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1567651335000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1567651335000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1567651335000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1567662150410"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1567662150410"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1567662150410"
webtalk_add_data -client sdk -key DebugCount -value "1" -context "sdk\\\\bsp/1567662150410"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1567662150410"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1567662150410"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1567662150410"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1567662150410"
webtalk_transmit -clientid 3924655224 -regid "" -xml /home/jorge/VivadoUSM/AXI_Adder_tree_throughput/AXI_Adder_tree_throughput.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/jorge/VivadoUSM/AXI_Adder_tree_throughput/AXI_Adder_tree_throughput.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/jorge/VivadoUSM/AXI_Adder_tree_throughput/AXI_Adder_tree_throughput.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
